### ISSUE TITLE
suporte a outros canais

### ISSUE THREAD

**Issue by sergiors** [renancarvalho/gshit#3]
Mais quanto ódio nesse coração :trollface:

**Comment by renancarvalho** [comment]
hehehe, eu acho um saco "ter que ler" o conteúdo do gshow.
Estou preparando um commit para deixar opcional. Se o usuário quiser esconder esportes ou noticias também será possível.. Tem gente que não gosta né.

**Comment by sergiors** [comment]
Huehue é muito ódio hahaha zuera

Mas parabéns pelo projeto. Faz um select de block dai o cara exclui ele :)
